name: e2e_eval_aime24

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - "verl/trainer/config/*.yaml"
      - .github/workflows/e2e_eval_aime24.yml
      - "tests/e2e/run_r1_distill_qwen_aime24_eval.sh"
      - "!verl/trainer/main_ppo.py"
      - "!verl/trainer/fsdp_sft_trainer.py"

# Declare permissions just read content.
permissions:
  contents: read

jobs:
  e2e_eval_aime24:
    runs-on: [self-hosted, l20-1]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      HF_HUB_ENABLE_HF_TRANSFER: 1
    container:
      image: hiyouga/verl:ngc-th2.6.0-cu120-vllm0.8.2
      options: --gpus all --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install hf_transfer
          pip3 install -e .[test,gpu,math]
      - name: Prepare aime24 dataset
        run: |
          ray stop --force
          python3 recipe/r1/data_process.py --task aime2024
      - name: Running generation and evaluation in aime2024
        run: | 
          ray stop --force
          bash tests/e2e/run_r1_distill_qwen_aime24_eval.sh