name: e2e_grpo

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
    paths:
      - "verl/**/*.py"
      - "tests/**/*.sh"
      - "verl/trainer/config/*.yaml"
      - .github/workflows/e2e_grpo.yml
      - "tests/e2e/*.sh"
      - "!verl/trainer/fsdp_sft_trainer.py"
      - "!recipe/**"

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare permissions just read content.
permissions: 
  contents: read

jobs:
  e2e_gsm8k_megatron-l20-0:
    runs-on: [self-hosted, l20-0]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      HF_HUB_ENABLE_HF_TRANSFER: 1
    container:
      image: whatcanyousee/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te2.0-megatron0.11.0-v0.0.6
      options: --gpus all --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install hf_transfer
          pip3 install -e .[test]
      - name: Prepare gsm8k dataset
        run: |
          python3 examples/data_preprocess/gsm8k.py
      - name: Running GRPO gsm8k e2e training tests with FSDP on 8 L20 GPUs (Qwen)
        run: |
          ray stop --force
          bash tests/e2e/run_qwen_grpo.sh
      - name: Running GRPO gsm8k e2e training tests with 3D parallelism on 8 L20 GPUs with Megatron (Qwen)
        run: |
          ray stop --force
          bash tests/e2e/run_qwen_grpo_megatron.sh
  e2e_gsm8k_megatron-l20-1:
    runs-on: [self-hosted, l20-1]
    timeout-minutes: 40 # Increase this timeout value as needed
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      HF_HUB_ENABLE_HF_TRANSFER: 1
    container:
      image: whatcanyousee/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te2.0-megatron0.11.0-v0.0.6
      options: --gpus all --shm-size=10g
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Install the current repository
        run: |
          pip3 install hf_transfer
          pip3 install -e .[test]
      - name: Prepare gsm8k dataset
        run: |
          python3 examples/data_preprocess/gsm8k.py
      - name: Running GRPO gsm8k e2e training tests with FSDP on 8 L20 GPUs (Deepseek)
        run: |
          ray stop --force
          bash tests/e2e/run_deepseek_grpo.sh
      - name: Running GRPO gsm8k e2e training tests with 3D parallelism on 8 L20 GPUs with Megatron (Deepseek)
        run: |
          ray stop --force
          bash tests/e2e/run_deepseek_grpo_megatron.sh